# Generated by Django 3.0.8 on 2020-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuulname', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
